[workspace]
members = [
    "da",
    "rt-evm/api",
    "rt-evm/mempool",
    "rt-evm/executor",
    "rt-evm/storage",
    "rt-evm/blockmgmt",
    "rt-evm/model",
    "rt-evm/utils/crypto",
]
resolver = "2"

[workspace.dependencies]
rt-evm-api = { path = "rt-evm/api" }
rt-evm-mempool = { path = "rt-evm/mempool" }
rt-evm-executor = { path = "rt-evm/executor" }
rt-evm-storage = { path = "rt-evm/storage", default-features = false }
rt-evm-blockmgmt = { path = "rt-evm/blockmgmt" }
rt-evm-model = { path = "rt-evm/model" }
rt-evm-crypto = { path = "rt-evm/utils/crypto" }
da = { path = "da" }

evm = { version = "0.41", features = ["with-serde"] }
ethereum = { version = "0.15", features = ["with-serde"] }
ethereum-types = "0.14"
ethabi = "18.0.0"
ethers = "2.0.9"
futures-core = "0.3.29"
futures-util = "0.3.29"
hex = "0.4.3"
log = "0.4.20"

beef = "0.5"
jsonrpsee = { version = "0.15", features = ["http-server", "macros", "ws-server"] }
anyhow = "1"

toml = "0.7.6"
rlp = "0.5"
rlp-derive = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
faster-hex = "0.6"
bcs = "0.1.5"
bytes = { version = "1.4", features = ["serde"] }
derive_more = "0.99"

ophelia = "0.3"
ophelia-secp256k1 = "0.3"

moka = "0.10.0"
rayon = "1.7.0"
tokio = { version = "1.26", features = ["full"] }
parking_lot = "0.12.1"
once_cell = "1.17.1"
arc-swap = "1.6"
async-trait = "0.1"

az = "1.2"
bn = { package = "substrate-bn", version = "0.6" }
rug = "1.19"
sha2 = "0.10"
ripemd = "0.1"

ruc = { version = "5.0.10", features = ["crypto", "cmd", "ssh"] }
vsdb = { version = "0.62.0", default-features = false, features = ["rocks_backend","extra_types"] }
vsdb_trie_db = "0.21"
bitcoin = "0.31.1"
bitcoincore-rpc = "0.18.0"

ipfs-api-backend-hyper = { version = "0.6.0", features = ["with-send-sync"] }
ipfs-api = { version = "0.17.0", features = ["with-hyper-rustls"], default-features = false }

####################################################################
####################################################################

[package]
name = "novolited"
version = "0.1.0"
edition = "2021"
authors = []
license = "GPLv3"
build = "build.rs"

[[bin]]
name = "novolite"
path = "src/novolite.rs"

[dependencies]
ruc = { workspace = true }
vsdb = { workspace = true }
once_cell = { workspace = true }
bcs = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

rt-evm-api = { workspace = true }
rt-evm-mempool = { workspace = true }
rt-evm-executor = { workspace = true }
rt-evm-storage = { workspace = true }
rt-evm-blockmgmt = { workspace = true }
rt-evm-model = { workspace = true }
da = { workspace = true }

ethers = { workspace = true }

tokio = { workspace = true }

clap = { version = "4.0", features = ["derive"] }

env_logger = "0.10.0"
log = { workspace = true }

[features]
default = ["vsdb_compress", "vsdb_bcs_codec"]
vsdb_compress= ["vsdb/compress"]

ruc_compact = ["ruc/compact"]

vsdb_bcs_codec = ["rt-evm-storage/vsdb_bcs_codec"]
vsdb_json_codec = ["rt-evm-storage/vsdb_json_codec"]
vsdb_msgpack_codec = ["rt-evm-storage/vsdb_msgpack_codec"]

[build-dependencies]
vergen = "7"

[patch.crates-io]
#vsdb = { git = "https://github.com/FindoraNetwork/vsdb", tag = "trie-full-history" }
#keccak-hasher = { git = "https://github.com/FindoraNetwork/trie", tag = "v0.27.1-full-history" }
#hash-db = { git = "https://github.com/FindoraNetwork/trie", tag = "v0.27.1-full-history" }
#trie-db = { git = "https://github.com/FindoraNetwork/trie", tag = "v0.27.1-full-history" }
#reference-trie = { git = "https://github.com/FindoraNetwork/trie", tag = "v0.27.1-full-history" }
