file = false
file_path = ""
ipfs = false
ipfs_url = ""
celestia = false
celestia_url = ""
celestia_token = ""
celestia_namespace_id = ""
greenfield = true
greenfield_rpc_addr = "https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org:443"
greenfield_chain_id = "greenfield_5600-1"
greenfield_bucket = "bucket123123123"
greenfield_password_file = "/tmp/password"
default = "greenfield"

electrs_url = "tcp://127.0.0.1:60401"
btc_url = "http://127.0.0.1:18443"
username = "admin1"
password = "123"
network = "regtest"

eth_url = "http://127.0.0.1:8545"
chain_id = 65535
