default_da = "greenfield"

[greenfield]
rpc_addr = "https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org:443"
chain_id = "greenfield_5600-1"
bucket = "bucket123123123"
password_file = "/tmp/password"

[btc]
electrs_url = "tcp://127.0.0.1:60401"
btc_url = "http://127.0.0.1:18443"
username = "admin1"
password = "123"
network = "regtest"

[node]
chain_id = 65535