[package]
name = "tx_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }

bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
ethers = { workspace = true }

electrum-client = "0.19.0"